NUM_NPCS = 15
NUM_PCS = 0
PACE = 50
ATTACK_TIMER_MAX = 2.0
SIZE = 10 -- character size
SWORD_LENGTH = 20
SWORD_SWEEP = 540
DEBUG = false


FLOCK_NEIGHBORHOOD = 150
FLOCK_NEIGHBORHOOD_ANGLE = 120 -- angle from front of sheep, degrees
FLOCK_COHESION = 0.5
FLOCK_SEPARATION = 0.5
FLOCK_ALIGNMENT = 0.125
SHEEP_INITIATIVE = 0
DECAY = 0.9
GRAIN_DESIRE = 1.0
THREAT_AVOID = 1.0
OBSTACLE_AVOID = 1.0
OBSTACLE_NEIGHBORHOOD = 100



WIGGLE_RANGE = 0.1963 -- that's pi / 16
WIGGLE_RATE = 0.02

-- Time characters rush onto the screen after spawning.
RUSH_TIME = 3.0

BAA_TIMER_MAX = 3.0