NUM_NPCS = 15
NUM_PCS = 0
PACE = 50
ATTACK_TIMER_MAX = 2.0
SIZE = 10 -- character size
SWORD_LENGTH = 20
SWORD_SWEEP = 540
DEBUG = false


FLOCK_NEIGHBORHOOD = 150
FLOCK_NEIGHBORHOOD_ANGLE = 120 -- angle from front of sheep, degrees
FLOCK_COHESION = 0.5
FLOCK_SEPARATION = 0.5
FLOCK_ALIGNMENT = 0.125
SHEEP_INITIATIVE = 0
DECAY = 0.9
